config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :rooms
  resources :book_rooms
  resources :customers
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book_room.rb
class BookRoom < ApplicationRecord
  belongs_to :room
  belongs_to :customer

  validates_presence_of :checkIn, :checkOut
end

app/controllers/book_rooms_controller.rb
class BookRoomsController < ApplicationController
  before_action :authenticate, only: [:create, :update, :destroy]
  before_action :set_book_room, only: %i[ show edit update destroy ]

  # GET /book_rooms or /book_rooms.json
  def index
    @book_rooms = BookRoom.all
  end

  # GET /book_rooms/1 or /book_rooms/1.json
  def show
  end

  # GET /book_rooms/new
  def new
    @book_room = BookRoom.new
  end

  # GET /book_rooms/1/edit
  def edit
  end

  # POST /book_rooms or /book_rooms.json
  def create
    @book_room = BookRoom.new(book_room_params)
    @room = Room.find_by(id: book_room_params[:room_id])

    if @room.isAvailable && @room.checkOutDate.nil?
      @room.update(isAvailable: false, checkOutDate: book_room_params[:checkOut])
    elsif @room.checkOutDate.present? && Date.parse(book_room_params[:checkIn]) < @room.checkOutDate
      @book_room.errors.add(:base, "Room is booked on that day.")
    end

    respond_to do |format|
      if @book_room.errors.any?
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_room.errors, status: :unprocessable_entity }
      elsif @book_room.save
        @book_room.room.update(checkOutDate: @book_room.checkOut)
        format.html { redirect_to book_room_url(@book_room), notice: "Book room was successfully created." }
        format.json { render :show, status: :created, location: @book_room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_rooms/1 or /book_rooms/1.json
  def update
    respond_to do |format|
      if @book_room.update(book_room_params)
        format.html { redirect_to book_room_url(@book_room), notice: "Book room was successfully updated." }
        format.json { render :show, status: :ok, location: @book_room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_rooms/1 or /book_rooms/1.json
  def destroy
    @book_room.destroy

    respond_to do |format|
      format.html { redirect_to book_rooms_url, notice: "Book room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def authenticate
      unless logged_in?
        redirect_to user_session_path, notice: 'Please log in'
      end
    end

    def logged_in?
      user_signed_in?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_book_room
      @book_room = BookRoom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_room_params
      params.require(:book_room).permit(:checkIn, :checkOut, :description, :room_id, :customer_id)
    end
end

app/helpers/book_rooms_helper.rb
module BookRoomsHelper
end

app/views/book_rooms/_book_room.html.erb
<div id="<%= dom_id book_room %>">
  <p>
    <strong>Check In:</strong>
    <%= book_room.checkIn %>
  </p>

  <p>
    <strong>Check Out:</strong>
    <%= book_room.checkOut %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book_room.description %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= book_room.room_id %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= book_room.customer_id %>
  </p>

</div>

app/views/book_rooms/_form.html.erb
<%= form_with(model: book_room) do |form| %>
<% if book_room.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(book_room.errors.count, "error") %> prohibited this book_room from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% book_room.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :checkIn, class: label_class %>
          <%= form.date_field :checkIn, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :checkOut, class: label_class %>
          <%= form.date_field :checkOut, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :description, class: label_class %>
          <%= form.text_field :description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :room_id, class: label_class %>
          <%= form.collection_select :room_id, Room.all, :id, :id, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :customer_id, class: label_class %>
          <%= form.collection_select :customer_id, Customer.all, :id, :fullName ,class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if book_room.persisted? %>
<%= link_to "Cancel", book_room, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", book_rooms_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/book_rooms/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit Booking</h1>
    <% if @book_room.persisted? %>
    <%= button_to 'Destroy', @book_room, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', book_room: @book_room %>
</div>

app/views/book_rooms/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Book Rooms</h1>

    <%= link_to new_book_room_path, class: button_class(theme: "primary") do %>
    Booking a room
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>

                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-center">Checkin</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-center">Checkout</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-center">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-center">Room</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-center">Customer</th>

          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>

      </tr>
    </thead>

    <tbody>
      <% @book_rooms.each do |book_room| %>
      <%= content_tag :tr, id: dom_id(book_room), class: dom_class(book_room) do %>


              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400 text-center"><%= book_room.checkIn %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400 text-center"><%= book_room.checkOut %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400 text-center"><%= book_room.description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400 text-center"><%= book_room.room.id %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400 text-center"><%= book_room.customer.fullName %></td>


        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400 text-center"><%= link_to 'Show', book_room %></td>

      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/book_rooms/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">Booking ...</h1>

  <%= render 'form', book_room: @book_room %>
</div>

app/views/book_rooms/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Book_room</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to book_rooms_path, class: button_class(theme: "transparent") do %>
      All Book_rooms
      <% end %>
      <%= link_to edit_book_room_path(@book_room), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Check In:</p>
        <p><%= @book_room.checkIn %></p>
      </li>
      <li>
        <p class="font-semibold">Check Out:</p>
        <p><%= @book_room.checkOut %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @book_room.description %></p>
      </li>
      <li>
        <p class="font-semibold">Room:</p>
        <p><%= @book_room.room.id %></p>
      </li>
      <li>
        <p class="font-semibold">Customer:</p>
        <p><%= @book_room.customer.fullName %></p>
      </li>
  </ul>
</div>